export {default as Main} from "./Main"
export {default as Index} from "./Index"
export {default as Navbar} from "./Navbar"
export {default as About} from "./About"
export {default as Portfolio} from "./Portfolio"